org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
org.gradle.daemon=false
org.gradle.vfs.watch=false
org.gradle.parallel=false
# android.suppressUnsupportedCompileSdk=35
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=true
